### ISSUE TITLE
Conflict issue on submitting data on Firefox Mobile devices

### ISSUE THREAD

**Issue by webVerts** [digitalfortress-tech/typeahead-standalone#54] opened 2023-04-12 17:46 UTC
### What happened?

Tested on Firefox Mobile and Mull Browser.

Open FF mobile app(Android)
- Visit `https://url.authifyweb.com/`
- Type the the word `nykaa`. => 3 suggestions should appear
- select the word `Nykaa`, submit.

Result:
Received different results
- Nothing happens. the suggestions list gets closed, but nothing more.
- The tt-input form inserts few extra letters automatically.(See attached video)
- After submitting 3 or 4 times it works and submit the data. 

Expected Output:
The word `Nykaa` gets selected and the a form to submit URL appears.

preventSubmit is: False

On chrome mobile it works as expected.

https://user-images.githubusercontent.com/100699190/231539718-a1ad2826-d9a4-4407-a000-8e1624a15027.mp4

JS code: https://github.com/authifyWeb/authifyURL/blob/main/resources/script.js
repo : `https://github.com/authifyWeb/authifyURL`

### Affected version

Latest

### Reproduction URL

https://github.com/authifyWeb/authifyURL

### How to reproduce?

Open FF mobile app(Android)

- Visit `https://url.authifyweb.com/`
- Type the the word nykaa. => 3 suggestions should appear
- select the word Nykaa, submit.

### Browsers

Firefox

**Comment by niketpathak** [comment] 2023-04-12 21:22
Hello, 

Thank you for reporting this. I tried to reproduce the issue, but for me, things are working as expected. 

According to you, when the suggestion "Nykaa" is selected, you had different responses.

1. Nothing happens. the suggestions list gets closed, but nothing more. This is normal because your input element is outside of a form element, so until you do not hit the enter key on the keyboard, the onSubmit hook will not be called. For me, when the the enter key is presset, the onSubmit hook is called as expected.
2. The tt-input form inserts few extra letters automatically.(See attached video), I was not able to reproduce this issue at all. Tested on Browserstack (used several android devices, browser Firefox mobile)
3. After submitting 3 or 4 times it works and submits the data - again, you need to press the enter key or you need to put your input within a form and add a submit button so that the data gets submitted. You could also submit the form programatically if you'd like.

**Comment by webVerts** [comment] 2023-04-13 07:58
Using on MiA3, Android 10, FF: 111.1.1 . The problem doesn't appear on browserstack, when mouse is used to select the term.

When I submitted the previous issue, I forgot to mention it explicitly, but I am pressing the enter key after clicking the suggestion. 

I'm comparing FF with that of DDG browser and Brave on android, where the later browsers works fine.

the para ` Submit URL below .....  "name" ` will help in figuring out when the onSubmit hook is called.

- Search the term `dhan`. Two search result appears
- Select One of them.
    -  **Chrome & DDG**: The sugg list disappears and pressing the enter key, the onSubmit Hook is called.
    - **Firefox**: List sugg still appears, but now with only the selected suggestion in the list. Clicking enter key -> Nothing happens. Selecting the suggestion again, the list disappears. Clicking enter, now the on Submit hook is called.

The below case will further show how it affects on FF.
- Search for the term `India`. 7 suggestions appear.
- Select/click the term `Indian Bank`.
    - **Chrome**: Sugg list disappears, click enter onSubmit is called.
    - **Firefox**: Suggestion list show 3 items, where the word `Indian Bank` exists.

There lies the problem in FF, instead of selecting the term, it only further filters, so clicking enter has no action.
Could you please test it on an actual FF mobile browser.
_______________

Now the previous case example with `Nykaa`

2 : `The tt-input form inserts few extra letters automatically.`-> `Because as far as the input is concerned, we never concatenate text in the input field, it is always replaced with a new value`

Just keep in mind, I'm not a programmer, so I could be wrong here. Also this happens only on certain times

This problem might also be related with the very above case, where its filtering, instead of selecting. Because the new word that appears on the form is `Nykaanykaa`.

- So when selecting `nykaa` from the 3 suggested list, the lists still appears with the same 3 suggestions. This is because the word `nykaa` exist in 3 suggestion(Still filtering only). Clicking enter, onSubmit action is not called.
- So refreshing page-> serching `nykaa` -> clicking on the word `nykaa` suggestion 2 times since the list doesn't disappear(on the first click `nykaa` -> `Nykaa` on the form, second click list disappears) and then click on enter the word in the suggestion becomes `Nykaanykaa`

Also not just case for `Nykaa`.

Search term |  Result
|---|---|
`purple` | `Purpllepurplle` |
`Canara bank` | `Canara Bankbank ` |
`Axis bank` | `Axis Bankbank` |
`Axis Bank` | `Axis BankBank` |

Refer below video

The word that gets added as extra is the last input term. Also it appears only when typing the search full word. For example
* Search term `nykaa` and select `Nykaa Man` twice, and click enter. No issue
* Search term `nykaa` and select `Nykaa` twice, and click enter. -> Nykaanykaa
*  Search term `Nykaa man` and select the `Nykaa Man` from suggestion twice, click enter. -> Nykaa Manman 
* Search term `Nykaa Man` and select the `Nykaa Man` from suggestion twice, click enter. -> Nykaa ManMan 



https://user-images.githubusercontent.com/100699190/231690182-c91e31b1-7729-4808-b02d-44c1f989989e.mp4


Hope it helps

**Comment by niketpathak** [comment] 2023-04-13 08:39
Thank you for the detailed report. This will be checked out soon.

**Comment by webVerts** [comment] 2023-04-20 16:11
Not sure if it'll help, 

Test site: `urltest.pages.dev` Typeahead@4.18.0

case 2 : `The tt-input form inserts few extra letters automatically.`

For the below case extra letters are not being added, even when typing in the full word.

- Search the term `nykaa` 
- Submit enter without selecting anything. (Nothing happens, as there is no selection)
- Now select the item`Nykaa` from list. (List disappears. The word inside the search bar becomes `Nykaa`)
- Click enter.(onSubmit is called)

**Comment by niketpathak** [comment] 2023-04-21 09:07
I was unable to reproduce the extra letters that were being added. I tried this on a physical device (Firefox for Android). Although, there exists a small bug where even on selecting an item, the list does not close (which I think is due to the way Firefox handles "input" event). I have to do some indepth debugging to figure out if this is really something that Firefox needs to fix or something that is on our end (I will try to resolve it this weekend when I get some free time). 
Thank you for reporting.

**Comment by niketpathak** [comment] 2023-05-07 15:52
Hello, the firefox bug has been fixed in [v4.20.0](https://www.npmjs.com/package/typeahead-standalone/v/4.20.0)

**Closed by niketpathak** 2023-05-07 15:52 UTC
Labels: bug

**Comment by webVerts** [comment] 2023-06-05 06:18
@niketpathak 

The first issue is completely solved, though, the second where, it automatically enters few letters still exists for some use case. Though considering that most people might not use it this way, it's not a blocker or a major issue.

Site: `https://tasa.pages.dev/`  . It's your own example code for loading local source, with minor changes.
Running the latest version of Typeahead-Standalone
_______

Open Firefox Browser on a physical Android device.
Type in the color "blue". 
Select Blue from the dropdown. Press Submit. (Notice the text in Input Field change to "Blue")


| Action | Result in the input field |
|--|--|
| Enter Space| Blueblue |
|Enter 'q' | Blueblueq |
________
Again I don't think this is a major issue, as the use case is very small. Also the same issue can be observed for Twitter Typeahead examples. So this is probably a FF issue

**Comment by niketpathak** [comment] 2023-06-05 07:12
Hello, thank you for confirming that the initial bug has been resolved. However, i am still unable to reproduce the bug where extra characters are added. I tested on a physical Android device on Firefox Browser (v113.2.0 which was released on 22nd May 2023) Device used: Samsung galaxy S20. Here is a screencast to show you the same: 


https://github.com/digitalfortress-tech/typeahead-standalone/assets/10226768/5eed5103-126b-4578-a7b5-c147c9bf5539

**Comment by webVerts** [comment] 2023-06-05 08:13
@niketpathak 

Using the same version of browser.

From your screen share, I think you are not clicking enter after the selection.
After typing in blue. and selecting from dropdown. Click the enter(submit) button[That magnifying glass in keyboard]. Then press the space or any other character. 



https://github.com/digitalfortress-tech/typeahead-standalone/assets/100699190/545f4252-ab41-4cc2-972a-21dffbd0d987

**Comment by niketpathak** [comment] 2023-06-05 08:30
Hello, thank you for the video. I cannot understand how you are able to reproduce it. I did click the submit button as well but for me it works perfectly. Here's the proof -


https://github.com/digitalfortress-tech/typeahead-standalone/assets/10226768/883f36d4-56e0-4b97-8721-16200ee4ea82

**Comment by webVerts** [comment] 2023-06-05 10:29
Wierd. 
Anyway since it's not much of an issue, need not waste any time. BTW thanks for resolving the previous issue.
